language: python
python:
  - 3.4
  - 2.7
script: make test
notifications:
  email: false
env:
  matrix:
    - DJANGO='django>=1.6,<1.7'
    - DJANGO='https://github.com/django/django/archive/1.7c1.zip'
install:
  - pip install -r test_requirements.txt
  - pip install $DJANGO coveralls
after_success:
  coveralls
